FROM alpine:latest
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk update && \
    apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone \
ENV TZ=Asia/Shanghai

ARG SERVER_NAME=user
ARG SERVER_TYPE=rpc

ENV RUN_BIN=/${SERVER_NAME}/bin/${SERVER_NAME}-${SERVER_TYPE}
ENV RUN_CONF=/${SERVER_NAME}/conf/${SERVER_NAME}.yaml
# etc/conf 放置动态拉取的配置文件
RUN mkdir /$SERVER_NAME && mkdir /$SERVER_NAME/bin && mkdir /$SERVER_NAME/conf && mkdir -p /$SERVER_NAME/etc/conf

COPY ./bin/$SERVER_NAME-$SERVER_TYPE /$SERVER_NAME/bin

COPY ./apps/$SERVER_NAME/$SERVER_TYPE/etc/dev/${SERVER_NAME}.yaml /$SERVER_NAME/conf

RUN chmod +x /$SERVER_NAME/bin/$SERVER_NAME-$SERVER_TYPE

WORKDIR /$SERVER_NAME/bin

CMD $RUN_BIN -f $RUN_CONF




